---

# Should be able to query the version on any server system
- name: Check kubectl version
  ansible.builtin.command:
    cmd: kubectl version
  register: k3s_kubectl_check
  failed_when: k3s_kubectl_check.rc != 0

# Should be able to query list of namespaces
- name: Check kubectl namespace retrieve
  ansible.builtin.command:
    cmd: kubectl get ns
  register: k3s_kubectl_check
  failed_when: k3s_kubectl_check.rc != 0

# Should be able query each node in the play
- name: Check for nodes
  ansible.builtin.command:
    cmd: "kubectl get node {{ hostvars[item].ansible_hostname }}"
  register: k3s_kubectl_check
  failed_when: k3s_kubectl_check.rc != 0
  loop: "{{ play_hosts }}"
  run_once: true

# Install Helm Cli
- name: Helm cli install
  when: k3s_install_helmcli
  block:
    - name: Download helm release
      ansible.builtin.get_url:
        url: "{{ k3s_helm_release_url }}"
        dest: "{{ k3s_asset_directory }}/helm.tgz"
        mode: "0644"

    - name: Extract helm
      ansible.builtin.unarchive:
        extra_opts:
          - --strip-components=1
          - --wildcards
          - "*/helm"
        dest: /usr/local/bin
        group: root
        owner: root
        mode: "0755"
        # include: "*/helm"
        src: "{{ k3s_asset_directory }}/helm.tgz"
        remote_src: true
